# receives list of gly files, prints BibTeX commands citing sources referred to by the score metadata

require 'gly'

puts "% Generated by #{__FILE__}"

parser = Gly::Parser.new

ARGV.flat_map do |path|
  doc = parser.parse(path)
  doc.scores.collect do |score|
    book = score.headers['book']
    if book
      book.split(' ').first
    else
      nil
    end
  end
end
  .compact
  .uniq
  .each do |bibkey|
  puts "\\nocite{#{bibkey}}"
end
