GLY =
  if ENV['USER'] == 'igneus'
    # use the author's development setup
    '/home/igneus/antiphonale83/gly'
  else
    'gly'
  end

glys = Dir['cantus/*/*.gly'].collect do |gly_path|
  glytex_path = File.basename(gly_path).sub('.gly', '.tex')

  file glytex_path => [gly_path] do
    sh GLY, 'preview', '--no-document', gly_path
  end

  glytex_path
end

file 'annotationes.tex' => ['scripts/annotationes.rb'] + Dir['cantus/*/*.gly'] do |t|
  sh 'ruby', *t.prerequisites
end

calendars =
  ['1915.txt', '1947.txt'].collect do |src|
  target = src.sub('.txt', '.tex')

  file target => ['scripts/calendarium.rb', 'calendarium/' + src] do |t|
    sh 'ruby', *t.prerequisites
  end

  target
end

deps =
  Dir['*.tex'] +
  Dir['*.*bx'] +
  Dir['*.bib'] +
  glys +
  calendars +
  %w(
    annotationes.tex
  )

main = 'officia_propria_pragensia_1912.tex'
main_noext = main.sub '.tex', ''
main_pdf = main.sub '.tex', '.pdf'

file main_pdf => deps do |t|
  texargs = ['lualatex', '--interaction=nonstopmode', main_noext]
  sh *texargs
  sh 'biber', main_noext
  sh *texargs
end

task :default => [main_pdf]

desc 'smazat vedlejsi produkty sazby latexem'
task :clean do
  %w{aux bbl dvi bcf blg log out pdf run.xml *~}.each do |s|
    unless Dir['*.'+s].empty?
      sh "rm *."+s
    end
  end
end
