---
# bibliography of the sources
cbre:
  siglum: CZ-Pn XV A 10
  name: Vesperarium svatovítské
  year: 1370-1380
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XV_A_10_____0MGV3O0-cs"
hr1:
  siglum: CZ-HKm Hr-1
  name: Antifonář latinský
  year: 14xx
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-MVCHK_HR_1_II_A_1_33SY9L6-cs"
hr3:
  siglum: CZ-HKm Hr-3
  name: Antifonář latinský - letní část
  year: -1470
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-MVCHK_HR_3_II_A_3_0JI5247-cs"
hr4:
  siglum: CZ-HKm Hr-4
  name: Antifonář latinský - zimní část
  year: -1470
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-MVCHK_HR_4_II_A_4_2F5P07D-cs"
kol1:
  siglum: CZ-Pn XII A 22
  name: Kolínský antifonář - I. díl
  year: -1477
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_22____0YK1T6C-cs"
kol2:
  siglum: CZ-Pn XII A 21
  name: Kolínský antifonář - II. díl
  year: 1470-1499
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_21____30TXYP6-cs"
nic:
  siglum: CZ-Pn XII A 24
  name: Zimní antifonář plzeňského faráře Mikuláše
  year: 1412
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_24____3UQDTL9-cs"
olm:
  siglum: CZ-OLm K 14892
  name: Antifonář
  year: 138x
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-VMO___K_14892_____2I4Z3A2-cs"
pint:
  siglum: CZ-PLm 504 C 004
  name: Antiphonarium Plsnense
  year: 1616
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-ZMP___504_C_004___107P3BA-cs"
  notice: only contains antiphon incipits/intonations and verses for responsories
plf:
  siglum: CZ-PLm 510 C 004
  name: fragmentum antiphonarii
  year: 12xx
  uri: http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-ZMP___510_C_004___01T18V7-cs
pvi1:
  siglum: CZ-Pak P6/1
  name: Antifonář Arnošta z Pardubic - I. díl
  year: 1364, but with obvious later modifications
pvi2:
  siglum: CZ-Pak P6/2
  name: Antifonář Arnošta z Pardubic - II. díl
  year: 1364, but with obvious later modifications
pvi3:
  siglum: CZ-Pak P6/3
  name: Antifonář Arnošta z Pardubic - III. díl
  year: 1364, but with obvious later modifications
brv:
  siglum: SK-BRsa SNA 17
  name: Bratislavský antifonář V
  year: 14xx
  uri: http://cantus.sk/source/6775
aopc:
  name: Antiphonarium o[mn]ia pia Canonicarum horarum cantica, secundum ordinem atque usum Ecclesie et diocesis Monasteriensis
  year: 1537
  uri: http://daten.digitale-sammlungen.de/bsb00090351/image_1
opraem34:
  name: |
    Supplementum Antiphonarii pro eclesiis Montis Sion,
    Siloensi et Neorisensi,
    in: Antiphonarium ad usum ... Ordinis Praemonstratensis
  location: Parisiis - Tornaci - Romae
  publisher: Desclée
  year: 1934
propraem32:
  name: |
    Supplementum Processionalis pro ecclesiis Montis Sion,
    Siloensi et Neorisensi,
    in: Processionale ad usum ... Ordinis Praemonstratensis
  location: Parisiis - Tornaci - Romae
  publisher: Desclée
  year: 1932
li93:
  name: S. Joannis Nepomuceni Sacerdotis et Martyris Ad Laudes matutinas et ad Vesperas
  location: Praha
  publisher: Liturgický institut
  year: 1993
pustet1875:
  name: Vesperale Romanum juxta ordinem Breviarii Romani cum cantu emendato
  location: Ratisbonae, Neo Eboraci et Cincinnatii
  publisher: Fridericus Pustet
  year: 1875
  uri: https://books.google.cz/books?id=Xc4HAAAAQAAJ
  notice: |
    Chants of St. John Nepomuk in the same extent and with the same tones
    as in pustet1879, except of the pieces transcribed
    and not having notated alleluia at the antiphons.
pustet1879:
  name: Vesperale Romanum juxta ordinem Breviarii Romani cum cantu emendato
  location: Ratisbonae, Novae Eboraci et Cincinnatii
  publisher: Fridericus Pustet
  year: 1879
pustet1882:
  name: Vesperale Romanum juxta ordinem Breviarii Romani cum cantu emendato
  location: Ratisbonae, Neo Eboraci et Cincinnatii
  publisher: Fridericus Pustet
  year: 1882
  uri: https://books.google.cz/books?id=qtVDQ122UxEC
  notice: |
    Chants of St. John Nepomuk in the same extent and with the same tones
    as in pustet1879, except of the pieces transcribed.
orgpustet1890:
  author: Jos. Hanisch
  name: Organum comitans ad Vesperale Romanum juxta cantum authenticum
  edition: 3
  location: Ratisbonae, Neo Eboraci et Cincinnatii
  publisher: Fridericus Pustet
  year: 1890
  notice: |
    Chants of St. John Nepomuk in the same extent and with the same tones
    as in pustet1879, except of the pieces transcribed.
eins1774:
  name: Antiphonale benedictinum dispositum iuxta breviarium Einsidlense cum antiphonis etiam Boemiae propriis congestum a loci professo Fr. Vito A. D. 1774
  year: 1774
  # It seems the library doesn't have a RISM siglum assigned.
  # It's definitely not CZ-Pst
  # http://www.rism.info/typo3conf/ext/user_apachesolr/result.php?q=id:30003245
  # The hottest candidate is CZ-Ps
  # http://www.rism.info/typo3conf/ext/user_apachesolr/result.php?q=id:30002669 ?
  library: Knihovna Královské kanonie premonstrátů na Strahově, Praha
  shelfmark: DE II 28
einsric:
  name: Antiphonale Romano-Monasticum Breviario novo Einsidlensi accommodatum
  subtitle: VIrgInI In CoeLos assVMptae DICaVIt. AB.
  year: 1771 # encoded in the subtitle/dedication
  library: private library of prof. Luca Ricossa
  uri: https://yadi.sk/a/30zaT0_63VxMg8
  notice: |
    The formulary of St. John of Nepomuk is included in the main
    corpus of the antiphonary, the formulary of st. Venceslas
    is in a later supplement (of course - the texts were created
    only for the 1865 new edition of the "proprium Bohemiae"),
    without page numbering.
osbpav:
  name: Compendium Antiphonarii Monastici kalendario generali Ordinis Sancti Benedicti accommodatum
  location: Solesmis
  publisher: E typographeo Sancti Petri
  year: 1894
  library: private library of Jakub Pavlík
  notice: |
    Title page carries owner's signature: "Binder Raimund";
    the chants of interest are in a handwritten supplement
    of 8 numbered pages, containing two formularies
    (S. Joannis Nepom. Mart., S. Wenceslai Mart.),
    one antiphon for the feast "S. Ursulae et Soc. Vg. M."
    and a series of collects for Czech (Benedictine) feasts.
prosch:
  author: Franciscus Proschwitzer
  name: Manuale rituum ad usum directorum chori provinciae Pragensis
  location: Pragae
  year: 1894
  publisher: Francl
  notice: |
    Section "Antifony, verše a responsorie o svatých Patronech
    chrámů Páně" contains Magnificat antiphons and versicles
    for selected feasts, among them a small selection of feasts
    from the provincial proper.
vilsecker:
  author: F. J. Vilsecker
  name: Vesperae Breviarii Romani cantu chorali auctae
  location: Landishuti
  publisher: J. G. Wölfle
  year: 1844
  uri: https://books.google.cz/books?id=755IAAAAcAAJ
  notice: |
    In the roman-numbered part at the back of the volume
    on page CXXIII begins section "Officia propria sanctorum,
    aliquibus in regnis et provinciis ex indulto apostolico recitanda,"
    containing proper formularies for countries of the Austrian Empire,
    including many labeled "Pro regno Bohemiae".
    The book is present in a library in České Budějovice, which inherited it
    from the library of the local Redemptorist monastery.
    https://katalog.cbvk.cz/arl-cbvk/cs/detail-cbvk_us_cat-0578778-Vesperae-breviarii-romani-cantu-chorali-auctae-cum-officiis-sanctorum-per-summos-pontifices-novissi/
    So there's a chance that the chants were actually used
    (at least in this one institution) in Czech lands.
    The author was director of music in the St. Paul parish church, Passau.
vilsecker1856:
  author: F. J. Vilsecker
  name: Vesperae Breviarii Romani cantu chorali auctae
  location: Landishuti
  publisher: J. G. Wölfle
  year: 1856
  uri: https://books.google.cz/books?id=SVUwAQAAIAAJ
  notice: |
    The formulary of St. John Nepomuk is an identical
    re-edition from vilsecker.
schlecht:
  author: Raymund Schlecht
  name: Die Vespern nach dem römischen Breviere
  location: Nördlingen
  publisher: C. H. Beck
  year: 1852
  uri: https://books.google.cz/books?id=drFIAAAAcAAJ
  notice: |
    The author was active and the book received approbation
    in the German diocese of Eichstätt.
    Chant tunes are simplified for the sake of a more lively singing
    with organ accompaniment, as explained in the preface.
    For antiphons only incipits are notated,
    "da dieselben nach dem allgemeinen Gebrauche immer nur
    angestimmt und mit der Orgel fortgesetzt werden;
    die vollständinge Aufnahme der Gesangsweisen das Werk zu sehr
    vergrößerte und vertheuerte." (preface, p. V)
zsass:
  author: Franciscus Zsasskovszky
  name: Manuale musico-liturgicum (Chorálna kniha obriadov cirkewných)
  location: Agriae
  publisher: Lyceum Archi-episcopale
  year: 1853
  uri: https://books.google.cz/books?id=1alIAAAAcAAJ
  notice: |
    Latin-Slovak chant book of the diocese of Eger (lat. Agria), Hungary.
    This is a book with very limited liturgical repertory,
    for the feast we are interested in only proper hymns are included
    and the tunes are not really proper, but shared by a whole group
    of structurally similar hymns.
