---
# bibliography of the sources
kol1:
  siglum: CZ-Pn XII A 22
  name: Kolínský antifonář - I. díl
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_22____0YK1T6C-cs"
kol2:
  siglum: CZ-Pn XII A 21
  name: Kolínský antifonář - II. díl
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_21____30TXYP6-cs"
nic:
  siglum: CZ-Pn XII A 24
  name: Zimní antifonář plzeňského faráře Mikuláše
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_24____3UQDTL9-cs"
cbre:
  siglum: CZ-Pn XV A 10
  name: Vesperarium svatovítské
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XV_A_10_____0MGV3O0-cs"
pint:
  siglum: CZ-PLm 504 C 004
  name: Antiphonarium Plsnense
  year: 1616
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-ZMP___504_C_004___107P3BA-cs"
  notice: only contains antiphon incipits/intonations and verses for responsories