---
# bibliography of the sources
cbre:
  siglum: CZ-Pn XV A 10
  name: Vesperarium svatovítské
  year: 1370-1380
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XV_A_10_____0MGV3O0-cs"
hr1:
  siglum: CZ-HKm Hr-1
  name: Antifonář latinský
  year: 14xx
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-MVCHK_HR_1_II_A_1_33SY9L6-cs"
hr3:
  siglum: CZ-HKm Hr-3
  name: Antifonář latinský - letní část
  year: -1470
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-MVCHK_HR_3_II_A_3_0JI5247-cs"
hr4:
  siglum: CZ-HKm Hr-4
  name: Antifonář latinský - zimní část
  year: -1470
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-MVCHK_HR_4_II_A_4_2F5P07D-cs"
kol1:
  siglum: CZ-Pn XII A 22
  name: Kolínský antifonář - I. díl
  year: -1477
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_22____0YK1T6C-cs"
kol2:
  siglum: CZ-Pn XII A 21
  name: Kolínský antifonář - II. díl
  year: 1470-1499
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_21____30TXYP6-cs"
nic:
  siglum: CZ-Pn XII A 24
  name: Zimní antifonář plzeňského faráře Mikuláše
  year: 1412
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-NMP___XII_A_24____3UQDTL9-cs"
olm:
  siglum: CZ-OLm K 14892
  name: Antifonář
  year: 138x
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-VMO___K_14892_____2I4Z3A2-cs"
pint:
  siglum: CZ-PLm 504 C 004
  name: Antiphonarium Plsnense
  year: 1616
  uri: "http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-ZMP___504_C_004___107P3BA-cs"
  notice: only contains antiphon incipits/intonations and verses for responsories
plf:
  siglum: CZ-PLm 510 C 004
  name: fragmentum antiphonarii
  year: 12xx
  uri: http://www.manuscriptorium.com/apps/index.php?direct=record&pid=AIPDIG-ZMP___510_C_004___01T18V7-cs
pvi1:
  siglum: CZ-Pak P6/1
  name: Antifonář Arnošta z Pardubic - I. díl
  year: 1364, but with obvious later modifications
pvi2:
  siglum: CZ-Pak P6/2
  name: Antifonář Arnošta z Pardubic - II. díl
  year: 1364, but with obvious later modifications
pvi3:
  siglum: CZ-Pak P6/3
  name: Antifonář Arnošta z Pardubic - III. díl
  year: 1364, but with obvious later modifications
brv:
  siglum: SK-BRsa SNA 17
  name: Bratislavský antifonář V
  year: 14xx
  uri: http://cantus.sk/source/6775
aopc:
  name: Antiphonarium o[mn]ia pia Canonicarum horarum cantica, secundum ordinem atque usum Ecclesie et diocesis Monasteriensis
  year: 1537
  uri: http://daten.digitale-sammlungen.de/bsb00090351/image_1